version: "3"

services:
    backend:
        build:
            context: .
            dockerfile: docker/backend/dev/Dockerfile
            args:
                - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${BACKEND_PORT}:8000
        volumes:
            - ./backend:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - backend

    scraper:
        build:
            context: .
            dockerfile: docker/scraper/dev/Dockerfile
            args:
                - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DATABASE=${POSTGRES_DATABASE}
                - POSTGRES_HOST=${POSTGRES_HOST}
                - POSTGRES_PORT=${POSTGRES_PORT}
        platform: linux/x86_64
        working_dir: /app
        volumes:
            - ./scraper:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - backend

    frontend:
        build:
            context: .
            dockerfile: docker/frontend/dev/Dockerfile
            args:
                - NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${FRONTEND_PORT}:5173
        volumes:
            - ./frontend:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - frontend

    db:
        image: postgres:${POSTGRES_IMAGE_VERSION}
        platform: linux/x86_64
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data:rw
        networks:
            - common
            - backend

networks:
    common:
    frontend:
    backend:

volumes:
    db_data:
