version: "3"

services:
    nginx:
        image: ghcr.io/uekat-studies-pp/uekat-studies-pp-project-nginx:${NGINX_IMAGE_TAG}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        depends_on:
            - backend
            - frontend
        networks:
            - backend
            - frontend

    backend:
        image: ghcr.io/uekat-studies-pp/uekat-studies-pp-project-backend:${BACKEND_IMAGE_TAG}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${BACKEND_PORT}:8100
        depends_on:
            - db
        networks:
            - backend

    scraper:
        image: ghcr.io/uekat-studies-pp/uekat-studies-pp-project-scraper:${SCRAPER_IMAGE_TAG}
        platform: linux/x86_64
        working_dir: /app
        depends_on:
            - db
        networks:
            - backend

    frontend:
        image: ghcr.io/uekat-studies-pp/uekat-studies-pp-project-frontend:${FRONTEND_IMAGE_TAG}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${FRONTEND_PORT}:5173
        networks:
            - frontend

    db:
        image: postgres:${POSTGRES_IMAGE_VERSION}
        platform: linux/x86_64
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data:rw
        networks:
            - backend

networks:
    frontend:
    backend:

volumes:
    db_data:
