version: "3"

services:
    backend:
        build:
            context: .
            dockerfile: docker/backend/dev/Dockerfile
            args:
                - RUST_IMAGE_VERSION=${RUST_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${BACKEND_PORT}:8000
        volumes:
            - ./backend:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - backend

    cron-app:
        build:
            context: .
            dockerfile: docker/cron-app/dev/Dockerfile
            args:
                - RUST_IMAGE_VERSION=${RUST_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${BACKEND_PORT}:8000
        volumes:
            - ./cron-app:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - backend

    frontend:
        build:
            context: .
            dockerfile: docker/node/dev/Dockerfile
            args:
                - NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${FRONTEND_PORT}:5173
        volumes:
            - ./frontend:/app:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - common
            - frontend

networks:
    common:
    frontend:
    backend:
